package ca.sfu.cs.factorbase.exception;


/**
 * Custom exception to wrap and throw the specific cause of an error.  Should be thrown when an
 * error occurs when attempting to extract data from a data source.
 */
public class DataExtractionException extends Exception {


    /**
     * Serial version - auto-generated by Eclipse.
     */
    private static final long serialVersionUID = -2844261251784379099L;


    /**
     * Used to wrap the root cause of an exception when attempting to extract data from a data source.
     *
     * @param message - useful message telling the user what has potentially gone wrong.
     * @param cause - the exception that caused the error to occur when extracting data from a data source.
     */
    public DataExtractionException(String message, Throwable cause) {
        super(message, cause);
    }
}