package ca.sfu.cs.factorbase.exception;


/**
 * Custom exception to wrap and throw the specific cause of an error.  Should be thrown when an
 * error occurs when attempting to access a database.
 */
public class DataBaseException extends Exception {


    /**
     * Serial version - auto-generated by Eclipse.
     */
    private static final long serialVersionUID = -6623897407612813075L;


    /**
     * Used to wrap the root cause of an exception when attempting to access a database.
     *
     * @param message - useful message telling the user what has potentially gone wrong.
     * @param cause - the exception that caused the error to occur when accessing a database.
     */
    public DataBaseException(String message, Throwable cause) {
        super(message, cause);
    }
}
