package ca.sfu.cs.factorbase.exception;


/**
 * Custom exception to wrap and throw the specific cause of an error.  Should be thrown when an
 * error occurs when attempting to compute the score for a Bayesian Network structure.
 */
public class ScoringException extends Exception {


    /**
     * Serial version - auto-generated by Eclipse.
     */
    private static final long serialVersionUID = 526269150042072120L;

    /**
     * Used to wrap the root cause of an exception when attempting to compute the score for a Bayesian Network
     * structure.
     *
     * @param message - useful message telling the user what has potentially gone wrong.
     * @param cause - the exception that caused the error to occur when computing the score.
     */
    public ScoringException(String message, Throwable cause) {
        super(message, cause);
    }
}